# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 20:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('depend_on', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='paths.Course')),
            ],
        ),
    ]
