# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='depend_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paths.Course'),
        ),
    ]
