# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0003_auto_20170925_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='depend_on',
            field=models.ManyToManyField(to='paths.Course'),
        ),
    ]
