# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0004_auto_20170927_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='depend_on',
            field=models.ManyToManyField(blank=True, to='paths.Course'),
        ),
    ]
