# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-01 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0006_auto_20170930_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='depend_on',
            field=models.ManyToManyField(blank=True, related_name='don', to='paths.Course'),
        ),
    ]
