# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-01 22:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0010_auto_20171001_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='path',
            name='base',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='base', to='paths.Course'),
        ),
    ]
