# Generated by Django 2.0.1 on 2018-01-21 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0013_auto_20180120_2035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
    ]
