# Generated by Django 2.0.1 on 2018-01-27 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0017_auto_20180127_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='photo',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='path',
            name='photo',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
    ]
