# Generated by Django 2.0.1 on 2018-01-27 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0018_auto_20180127_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='photo',
            field=models.ImageField(blank=True, default='media/dummyimage.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='path',
            name='photo',
            field=models.ImageField(blank=True, default='media/dummyimage.png', upload_to=''),
        ),
    ]
