# Generated by Django 2.0.1 on 2018-01-28 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0019_auto_20180127_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='path',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='paths.Path'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='photo',
            field=models.ImageField(blank=True, default='dummyimage.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='path',
            name='photo',
            field=models.ImageField(blank=True, default='dummyimage.png', upload_to=''),
        ),
    ]
