# Generated by Django 2.0.1 on 2018-01-28 06:37

from django.db import migrations, models
import paths.models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0021_auto_20180128_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='path',
            name='photo',
            field=models.ImageField(blank=True, default='dummyimage.png', upload_to=paths.models.get_directory),
        ),
    ]
