# Generated by Django 2.0.1 on 2018-01-29 15:03

from django.db import migrations, models
class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0023_course_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
