# Generated by Django 2.0.1 on 2018-01-29 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0024_auto_20180129_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='path',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
