# Generated by Django 2.0.2 on 2018-02-02 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0026_auto_20180129_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='slug',
        ),
    ]
