# Generated by Django 2.0.2 on 2018-02-06 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0027_remove_author_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='access_counter',
            field=models.IntegerField(default=0, verbose_name='Access Counts'),
        ),
        migrations.AddField(
            model_name='course',
            name='access_counter',
            field=models.IntegerField(default=0, verbose_name='Access Counts'),
        ),
        migrations.AddField(
            model_name='path',
            name='access_counter',
            field=models.IntegerField(default=0, verbose_name='Access Counts'),
        ),
    ]
